export const CREATE_ITEM = 'CREATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
export const SAVE_EDIT_ITEM = 'SAVE_EDIT_ITEM';
export const CANCEL_EDIT_ITEM = 'CANCEL_EDIT_ITEM';
export const UPDATE_FILTER_TERM = 'UPDATE_FILTER_TERM';
